apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods
  namespace: argocd1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: mainproj
        image: your-app-image:tag
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pods
  namespace: argocd1
spec:
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


