apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: argocd1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example-container
        image: your-image:tag
        ports:
        - containerPort: 8080

------------
apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: argocd1
spec:
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

